### ISSUE TITLE
Showing 0 in Pop, Poped and Suc columns

### ISSUE THREAD

**Issue by cycool29** [popclick/popclick#2]
Just curious why so many columns are 0.
![DeepinScreenshot_select-area_20210823094422](https://user-images.githubusercontent.com/88134003/130381167-f8c3dc4f-4853-47ff-a3ed-25e2c827696d.png)

Can someone upload some example image in README.md?

**Comment by ITdairy** [comment]
I think I found where the problem occurs.

The script seem not detecting my IP address at first so no pops are success after running.

![DeepinScreenshot_select-area_20210823132022](https://user-images.githubusercontent.com/88134003/130394491-1c311dcc-b0f1-49ca-baf1-96275eae8f43.png)

Even I use my wireless adapter, it still shows `is not valid IP address as we need`
Any fix?

**Comment by cycool29** [comment]
Any solution ??

**Comment by cycool29** [comment]
I've running about 2 hours and only number in `Init`, `Con` and `CD` increased. May I know **IS THIS NORMAL?**

I hope I can have a response or a comment  **INSTEAD OF A EMOJI**.

And please explain what is the meaning of `Pop` `Init` `Con` `CD` `Poped` `Suc` ?

**Comment by cycool29** [comment]
The output in Prometheus Exporter:

```
# HELP popcat_connection Open connections.
# TYPE popcat_connection gauge
popcat_connection{status="init"} 4 1629782457699
popcat_connection{status="cd"} 4 1629784172732
# HELP popcat_request_total Request counter with status.
# TYPE popcat_request_total counter
popcat_request_total{status="success"} 0 0
```

Is that means no single pops are counted?
Please answer **as soon as possible**, thx. @Haraguroicha

**Comment by Haraguroicha** [comment]
`Pop` is means worker initialized count
`Init` is means initializing workers count
`Con` is means concurrent working count
`CD` is means workers in colddown time period
`Poped` is means the pop count success by worker
`Suc` is means success count

**Comment by Haraguroicha** [comment]
as README said, we have pull out all of CDN bypass related code, so that might be resulted doesn't work, but you runned about 2 hours and without any error and success is wired
